config/routes.rb
Actressbook::Application.routes.draw do

  resources :offices

  resources :offer_logs

  resources :directors

  resources :actresses

  match '/users/choice_type' => 'users/choice_type#choice_type'

  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :registrations => "users/registrations",
  }

  root :to => 'actresses#index'

  

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :address, :caption, :id, :last_login, :logo, :mail2, :rep_name, :tel, :tel2, :user_id
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, :notice => 'Office was successfully created.' }
        format.json { render :json => @office, :status => :created, :location => @office }
      else
        format.html { render :action => "new" }
        format.json { render :json => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to @office, :notice => 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :rep_name %><br />
    <%= f.text_field :rep_name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.number_field :tel %>
  </div>
  <div class="field">
    <%= f.label :tel2 %><br />
    <%= f.number_field :tel2 %>
  </div>
  <div class="field">
    <%= f.label :mail2 %><br />
    <%= f.text_field :mail2 %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_area :caption %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :last_login %><br />
    <%= f.datetime_select :last_login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>Listing offices</h1>

<table>
  <tr>
    <th>Id</th>
    <th>User</th>
    <th>Address</th>
    <th>Rep name</th>
    <th>Tel</th>
    <th>Tel2</th>
    <th>Mail2</th>
    <th>Caption</th>
    <th>Logo</th>
    <th>Last login</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offices.each do |office| %>
  <tr>
    <td><%= office.id %></td>
    <td><%= office.user_id %></td>
    <td><%= office.address %></td>
    <td><%= office.rep_name %></td>
    <td><%= office.tel %></td>
    <td><%= office.tel2 %></td>
    <td><%= office.mail2 %></td>
    <td><%= office.caption %></td>
    <td><%= office.logo %></td>
    <td><%= office.last_login %></td>
    <td><%= link_to 'Show', office %></td>
    <td><%= link_to 'Edit', edit_office_path(office) %></td>
    <td><%= link_to 'Destroy', office, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @office.id %>
</p>

<p>
  <b>User:</b>
  <%= @office.user_id %>
</p>

<p>
  <b>Address:</b>
  <%= @office.address %>
</p>

<p>
  <b>Rep name:</b>
  <%= @office.rep_name %>
</p>

<p>
  <b>Tel:</b>
  <%= @office.tel %>
</p>

<p>
  <b>Tel2:</b>
  <%= @office.tel2 %>
</p>

<p>
  <b>Mail2:</b>
  <%= @office.mail2 %>
</p>

<p>
  <b>Caption:</b>
  <%= @office.caption %>
</p>

<p>
  <b>Logo:</b>
  <%= @office.logo %>
</p>

<p>
  <b>Last login:</b>
  <%= @office.last_login %>
</p>


<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>