config/routes.rb
Actressbook::Application.routes.draw do

  resources :offices

  resources :offer_logs

  resources :directors

  resources :actresses

  match '/users/choice_type' => 'users/choice_type#choice_type'

  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :registrations => "users/registrations",
  }

  root :to => 'actresses#index'

  

end

app/models/director.rb
class Director < ActiveRecord::Base
  attr_accessible :belong, :birthday, :id, :last_login, :photo, :profile, :sex, :user_id
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @directors }
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @director }
    end
  end

  # GET /directors/new
  # GET /directors/new.json
  def new
    @director = Director.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @director }
    end
  end

  # GET /directors/1/edit
  def edit
    @director = Director.find(params[:id])
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, :notice => 'Director was successfully created.' }
        format.json { render :json => @director, :status => :created, :location => @director }
      else
        format.html { render :action => "new" }
        format.json { render :json => @director.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /directors/1
  # PUT /directors/1.json
  def update
    @director = Director.find(params[:id])

    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to @director, :notice => 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @director.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.number_field :sex %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :profile %><br />
    <%= f.text_area :profile %>
  </div>
  <div class="field">
    <%= f.label :belong %><br />
    <%= f.text_field :belong %>
  </div>
  <div class="field">
    <%= f.label :last_login %><br />
    <%= f.datetime_select :last_login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<h1>Listing directors</h1>

<table>
  <tr>
    <th>Id</th>
    <th>User</th>
    <th>Photo</th>
    <th>Sex</th>
    <th>Birthday</th>
    <th>Profile</th>
    <th>Belong</th>
    <th>Last login</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directors.each do |director| %>
  <tr>
    <td><%= director.id %></td>
    <td><%= director.user_id %></td>
    <td><%= director.photo %></td>
    <td><%= director.sex %></td>
    <td><%= director.birthday %></td>
    <td><%= director.profile %></td>
    <td><%= director.belong %></td>
    <td><%= director.last_login %></td>
    <td><%= link_to 'Show', director %></td>
    <td><%= link_to 'Edit', edit_director_path(director) %></td>
    <td><%= link_to 'Destroy', director, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Director', new_director_path %>

app/views/directors/new.html.erb
<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @director.id %>
</p>

<p>
  <b>User:</b>
  <%= @director.user_id %>
</p>

<p>
  <b>Photo:</b>
  <%= @director.photo %>
</p>

<p>
  <b>Sex:</b>
  <%= @director.sex %>
</p>

<p>
  <b>Birthday:</b>
  <%= @director.birthday %>
</p>

<p>
  <b>Profile:</b>
  <%= @director.profile %>
</p>

<p>
  <b>Belong:</b>
  <%= @director.belong %>
</p>

<p>
  <b>Last login:</b>
  <%= @director.last_login %>
</p>


<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>