config/routes.rb
Actressbook::Application.routes.draw do

  resources :offices

  resources :offer_logs

  resources :directors

  resources :actresses

  match '/users/choice_type' => 'users/choice_type#choice_type'

  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :registrations => "users/registrations",
  }

  root :to => 'actresses#index'

  

end

app/models/offer_log.rb
class OfferLog < ActiveRecord::Base
  attr_accessible :actress_id, :director_id, :message, :offer_id, :receive_datetime, :send_datetime
end

app/controllers/offer_logs_controller.rb
class OfferLogsController < ApplicationController
  # GET /offer_logs
  # GET /offer_logs.json
  def index
    @offer_logs = OfferLog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @offer_logs }
    end
  end

  # GET /offer_logs/1
  # GET /offer_logs/1.json
  def show
    @offer_log = OfferLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @offer_log }
    end
  end

  # GET /offer_logs/new
  # GET /offer_logs/new.json
  def new
    @offer_log = OfferLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @offer_log }
    end
  end

  # GET /offer_logs/1/edit
  def edit
    @offer_log = OfferLog.find(params[:id])
  end

  # POST /offer_logs
  # POST /offer_logs.json
  def create
    @offer_log = OfferLog.new(params[:offer_log])

    respond_to do |format|
      if @offer_log.save
        format.html { redirect_to @offer_log, :notice => 'Offer log was successfully created.' }
        format.json { render :json => @offer_log, :status => :created, :location => @offer_log }
      else
        format.html { render :action => "new" }
        format.json { render :json => @offer_log.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offer_logs/1
  # PUT /offer_logs/1.json
  def update
    @offer_log = OfferLog.find(params[:id])

    respond_to do |format|
      if @offer_log.update_attributes(params[:offer_log])
        format.html { redirect_to @offer_log, :notice => 'Offer log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @offer_log.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offer_logs/1
  # DELETE /offer_logs/1.json
  def destroy
    @offer_log = OfferLog.find(params[:id])
    @offer_log.destroy

    respond_to do |format|
      format.html { redirect_to offer_logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offer_logs_helper.rb
module OfferLogsHelper
end

app/views/offer_logs/_form.html.erb
<%= form_for(@offer_log) do |f| %>
  <% if @offer_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer_log.errors.count, "error") %> prohibited this offer_log from being saved:</h2>

      <ul>
      <% @offer_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :offer_id %><br />
    <%= f.number_field :offer_id %>
  </div>
  <div class="field">
    <%= f.label :director_id %><br />
    <%= f.number_field :director_id %>
  </div>
  <div class="field">
    <%= f.label :actress_id %><br />
    <%= f.number_field :actress_id %>
  </div>
  <div class="field">
    <%= f.label :send_datetime %><br />
    <%= f.datetime_select :send_datetime %>
  </div>
  <div class="field">
    <%= f.label :receive_datetime %><br />
    <%= f.datetime_select :receive_datetime %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offer_logs/edit.html.erb
<h1>Editing offer_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer_log %> |
<%= link_to 'Back', offer_logs_path %>

app/views/offer_logs/index.html.erb
<h1>Listing offer_logs</h1>

<table>
  <tr>
    <th>Offer</th>
    <th>Director</th>
    <th>Actress</th>
    <th>Send datetime</th>
    <th>Receive datetime</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offer_logs.each do |offer_log| %>
  <tr>
    <td><%= offer_log.offer_id %></td>
    <td><%= offer_log.director_id %></td>
    <td><%= offer_log.actress_id %></td>
    <td><%= offer_log.send_datetime %></td>
    <td><%= offer_log.receive_datetime %></td>
    <td><%= offer_log.message %></td>
    <td><%= link_to 'Show', offer_log %></td>
    <td><%= link_to 'Edit', edit_offer_log_path(offer_log) %></td>
    <td><%= link_to 'Destroy', offer_log, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer log', new_offer_log_path %>

app/views/offer_logs/new.html.erb
<h1>New offer_log</h1>

<%= render 'form' %>

<%= link_to 'Back', offer_logs_path %>

app/views/offer_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Offer:</b>
  <%= @offer_log.offer_id %>
</p>

<p>
  <b>Director:</b>
  <%= @offer_log.director_id %>
</p>

<p>
  <b>Actress:</b>
  <%= @offer_log.actress_id %>
</p>

<p>
  <b>Send datetime:</b>
  <%= @offer_log.send_datetime %>
</p>

<p>
  <b>Receive datetime:</b>
  <%= @offer_log.receive_datetime %>
</p>

<p>
  <b>Message:</b>
  <%= @offer_log.message %>
</p>


<%= link_to 'Edit', edit_offer_log_path(@offer_log) %> |
<%= link_to 'Back', offer_logs_path %>